### ISSUE TITLE
Possible issue with gmane mailing lists. 

### ISSUE THREAD

**Issue by geekygirldawn** [MetricsGrimoire/MailingListStats#62]
Summary: mlstats seems to have parsed the **wrong** mailing list based on looking at the output while actually not seeming to download anything at all.

My env:

- mlstats --version 0.4 (cloned from the repo and installed today - 2016-03-01)
- Python 2.7.6
- mysql  Ver 15.1 Distrib 5.5.47-MariaDB
- 14.04.1-Ubuntu

Note: this is the first time I've run mlstats on this new server.

I tried to download the lkml list (Main Linux Kernel Mailing list) from: http://dir.gmane.org/gmane.linux.kernel 

Using this command:
`mlstats --db-user=*** --db-password=*** --db-name=mlstats_linux --report-file=/home/dawn/log_files/lkml.txt http://dir.gmane.org/gmane.linux.kernel`

The log report (see snippet below) indicates that it actually looked at: http://dir.gmane.org/gmane.linux.kernel.mm
This is the Memory Management list

Note: I already had a copy of this list in my database from a db dump that Jesus sent me. 

The log report made it look successful, but I don't think it actually did anything. It finished much too quickly and the downloads aren't appearing in the folder. This folder contains a single file named "0" with contents "???V?0"
 `~/.mlstats/compressed/dir.gmane.org/gmane.linux.kernel`

There is the only folder under
`~/.mlstats/compressed/dir.gmane.org/`

```
MLStats report
--------------

Total messages by domain name (only top 10 per list):
Mailing list         	Domain name                      	#  
----------------     	-----------                      	----
gmane.linux.kernel.mm	gmail.com                        	11502
gmane.linux.kernel.mm	redhat.com                       	9657
gmane.linux.kernel.mm	jp.fujitsu.com                   	8407
gmane.linux.kernel.mm	google.com                       	7213
gmane.linux.kernel.mm	linux-foundation.org             	6368
gmane.linux.kernel.mm	linux.vnet.ibm.com               	6270
gmane.linux.kernel.mm	public.gmane.org                 	5967
```

From the database:

```
[mlstats_linux]> SELECT COUNT(*) FROM messages where mailing_list_url="http://dir.gmane.org/gmane.linux.kernel.mm";
+----------+
| COUNT(*) |
+----------+
|   147035 |
+----------+

[mlstats_linux]> SELECT COUNT(*) FROM messages where mailing_list_url="http://dir.gmane.org/gmane.linux.kernel";
+----------+
| COUNT(*) |
+----------+
|        0 |
+----------+
```

But ... it seems to think it analyzed linux.kernel and not linux.kernel.mm

```
[mlstats_linux]> select * from mailing_lists where mailing_list_url = 'http://dir.gmane.org/gmane.linux.kernel';
+-----------------------------------------+--------------------+--------------+---------------------+
| mailing_list_url                        | mailing_list_name  | project_name | last_analysis       |
+-----------------------------------------+--------------------+--------------+---------------------+
| http://dir.gmane.org/gmane.linux.kernel | gmane.linux.kernel | NULL         | 2016-03-01 14:05:26 |
+-----------------------------------------+--------------------+--------------+---------------------+

[mlstats_linux]> select * from mailing_lists where mailing_list_url = 'http://dir.gmane.org/gmane.linux.kernel.mm';
+--------------------------------------------+-----------------------+--------------+---------------------+
| mailing_list_url                           | mailing_list_name     | project_name | last_analysis       |
+--------------------------------------------+-----------------------+--------------+---------------------+
| http://dir.gmane.org/gmane.linux.kernel.mm | gmane.linux.kernel.mm | NULL         | 2016-02-19 12:53:14 |
+--------------------------------------------+-----------------------+--------------+---------------------+
```

**Comment by geekygirldawn** [comment]
Just a quick note. I'm running mlstats now on http://dir.gmane.org/gmane.linux.network

It looks like it's running and files with content are being downloaded into:
`~/.mlstats/compressed/dir.gmane.org/gmane.linux.network`

So it looks like mlstats is working on my server, but just not for the particular list in the bug report above :)

**Comment by gpoo** [comment]
Is there any chance you had downloaded the linux.kernel.mm before? I don't see the connection.

Regarding to linux.kernel, it does not seems that is `mlstats` fault. You can open a browser with the URL and see retrieves.

For example, I opened http://download.gmane.org/gmane.linux.kernel/0/100 (to get the first 100 messages), and I got an empty page. However, if I do the same with other mailing list, I get the raw mbox.

**Comment by gpoo** [comment]
I tried http://download.gmane.org/gmane.linux.kernel/400000/400010 just to choose random number (400000 is high, though), and it shows messages from 2003. I believe it is a limitation in gmane, perhaps because that archive is particularly big.

The thing is, the gmane backend checks for no results to stop retrieving data, which makes sense (or made sense).

FWIW, I tried smaller numbers, so far 10000/10010 retrieves something. The fix may involve a lot of trial and error, but might slow down retrieving other archives.

**Comment by geekygirldawn** [comment]
In the short term, maybe I would be better off manually downloading the archives, since I really only need archives starting in 2004 when they converted to git?

I could pretty easily script something to wget the files.To do this, I assume I would need to:

- wget the files in batches using something like http://download.gmane.org/gmane.linux.kernel/400000/400010
- compress the files
- run python pymlstats/analyzer.py /path/to/mbox

Did I miss anything?

**Comment by geekygirldawn** [comment]
Hmmm, maybe not. There is something seriously wrong with the gmane archives for this list, I think?

http://download.gmane.org/gmane.linux.kernel/400000/400010 retrieves messages starting with 
Tue Mar 04 03:33:20 2003

http://download.gmane.org/gmane.linux.kernel/50000/50010 also retrieves messages starting with 
Tue Mar 04 03:33:20 2003

Same 2003 message dates for http://download.gmane.org/gmane.linux.kernel/10000/10010

A lot of the smaller numbers are returning blank pages:
http://download.gmane.org/gmane.linux.kernel/7000/7010

There are some other archives, but none of them are formats I'm familiar with and am not sure if any of them easily expose mbox files:
https://lkml.org/lkml/
http://lkml.iu.edu/hypermail/linux/kernel/
http://marc.info/?l=linux-kernel

**Comment by gpoo** [comment]
I think, it would be easier to use my `decoupling` branch (see pull request #59). It added a parameter offset to the Gmane constructor. Then, you can call the constructor with the offset from where you want to start retrieving.

Even more, using that branch you can adapt the script in the comment https://github.com/MetricsGrimoire/MailingListStats/pull/59#issuecomment-130118335

**Comment by gpoo** [comment]
BTW, I could merge the branch too (but better later, when I am not falling asleep :-)

**Comment by sduenas** [comment]
We had the same problem when we analyzed that list at first. For any reason, there are some indices that do not work. The first message is stored in index `7381` (I discovered it after some trial and error).

http://download.gmane.org/gmane.linux.kernel/7380/7381

You can trick `mlstats` to start fetching from that index creating a file named `7380`. The tool uses the files under `$HOME/.mlstats/compressed/dir.gmane.org/gmane.linux.kernel` to know which index is the next to ask for the next time you run it. So..:

```
$ touch $HOME/.mlstats/compressed/dir.gmane.org/gmane.linux.kernel/7380
$ mlstats --db-user xxxx --db-password xxxx --db-name xxxx "http://dir.gmane.org/gmane.linux.kernel"
Retrieving http://download.gmane.org/gmane.linux.kernel/7380/9380...
Retrieving http://download.gmane.org/gmane.linux.kernel/9380/11380...
Retrieving http://download.gmane.org/gmane.linux.kernel/11380/13380...
```

It will fail again. I remember there are some other indexes around there that return empty pages. That will make MailingListsStats to stop. When an empty page is reached, it should mean that there are no more messages to analyze but this is not the case with this. You will have do some trial and error to discover which the next valid index is.

This might help you. Indexes from 1583000 to 1819000 are valid.

**Comment by geekygirldawn** [comment]
Hmmm, when I do this, it still starts over at 0 every time rather than starting where it left off.

    $ touch $HOME/.mlstats/compressed/dir.gmane.org/gmane.linux.kernel/7380
    $ mlstats --db-user xxxx --db-password xxxx --db-name xxxx "http://dir.gmane.org/gmane.linux.kernel"

 I confirmed that a file named 7380 exists and is in the right place, but there is also a file called 0, which has a few chars of junk at the beginning.

    dawn:~/.mlstats/compressed/dir.gmane.org/gmane.linux.kernel$ ls
    0  7380

Of course, mlstats terminated almost immediately on this part of the archive.

**Comment by sduenas** [comment]
@geekygirldawn, I was using an older version. Anyway, you can simulate the same behavior inserting a row in `compressed_files` table, including which index (or mbox) was the last you "retrieved".

Execute the next query en the database and then, run again mlstats.

```
INSERT INTO compressed_files(url, mailing_list_url, status, last_analysis) VALUES ("http://download.gmane.org/gmane.linux.kernel/7380", "http://dir.gmane.org/gmane.linux.kernel", "visited", "2016-03-03");
```

**Comment by gpoo** [comment]
@sduenas @geekygirldawn I pushed an option to start from an arbitrary message on Gmane.

I have not tested the patch (hence, no pull request :-) You need to update master to make this patch work. Please, let me know whether it works or where it fails.

**Comment by geekygirldawn** [comment]
@sduenas the insert worked - it's off and running again, thanks!

@gpoo I'll give the patch a try when it inevitably fails and I need to restart it :)

**Comment by gpoo** [comment]
FWIW, I could tried it and made a small fix. Pushed the fix in master.

**Comment by geekygirldawn** [comment]
I'm not sure this is fixed. It was still running and hadn't failed (so I hadn't implemented your fix yet).

After this output:

    Retrieving http://download.gmane.org/gmane.linux.kernel/2169380/2171380...

It failed with this:
```
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (2006, 'MySQL server has gone away') [SQL: u'SELECT compressed_files.url AS compressed_files_url, compressed_files.mailing_list_url AS compressed_files_mailing_list_url, compressed_files.status AS compressed_files_status, compressed_files.last_analysis AS compressed_files_last_analysis \nFROM compressed_files \nWHERE compressed_files.url = %s'] [parameters: ('http://download.gmane.org/gmane.linux.kernel/7380',)]
```

Not surprising, I guess, since it was overnight, and nothing was happening in the db. I revived the db and checked to see if maybe it had stored a couple of messages at some point, but there are no messages from this list in the db

However, I tried to restart it (both with and without your offset) after doing a git pull on the mlstats repo and a reinstall. Now, I'm getting this:
```
0 messages analyzed
0 messages stored in database mlstats_linux
0 messages ignored by the parser
INFO: Everything seems to be ok.
```

And it just hangs until I kill it. 

I've confirmed that there are still no messages in the db for this list.

**Comment by gpoo** [comment]
> I'm not sure this is fixed. It was still running and hadn't failed (so I hadn't implemented your fix yet).

Not needed, except for verification. When I pushed it was after I tested it by myself :-)

Regarding to the other part:

`'MySQL server has gone away'`

Your MySQL instance stopped working for some reason. I would recommend you to check MySQL logs, or syslog.

> I've confirmed that there are still no messages in the db for this list.

It makes sense, because it stopped when still it was downloading. IIRC, the only update that should happen in the database is the one that keep tracks of the files downloaded.

What is the content of `~/.mlstats/compressed/dir.gmane.org/gmane.linux.kernel`?

**Comment by geekygirldawn** [comment]
~/.mlstats/compressed/dir.gmane.org/gmane.linux.kernel has 1082 files. I uncompressed and took a look at the last file it downloaded and confirmed that it has data from yesterday so I think it has all of the files. I just can't get mlstats to properly restart to do the analysis.

This is all I can get from mlstats:

```
$ mlstats --db-user ** --db-password ** --db-name mlstats_linux --report-file=/home/dawn/log_files/lkml.txt --report-file=/home/dawn/log_files/lkml.txt
0 messages analyzed
0 messages stored in database mlstats_linux
0 messages ignored by the parser
INFO: Everything seems to be ok.
```

**Comment by geekygirldawn** [comment]
hang on a minute. I think I need more caffeine. I completely mangled that mlstats command with a copy paste error.  I've restarted it now, and it's downloading a few more files ... hopefully of messages that came in after it failed last night. 

*goes off to apply more caffeine while I wait for it to start trying to analyze again*

**Comment by geekygirldawn** [comment]
It's still having issues. I ran it again, but it starts analyzing just the most recently downloaded files:

```
$ mlstats --db-user ** --db-password ** --db-name mlstats_linux --report-file=/home/dawn/log_files/lkml.txt "http://dir.gmane.org/gmane.linux.kernel"
Retrieving http://download.gmane.org/gmane.linux.kernel/2167380/2169380...
Retrieving http://download.gmane.org/gmane.linux.kernel/2169380/2171380...
Analyzing /home/dawn/.mlstats/compressed/dir.gmane.org/gmane.linux.kernel/2167380
1462 messages analyzed
1462 messages stored in database mlstats_linux
0 messages ignored by the parser
INFO: Everything seems to be ok.
```

I tried it again just to be sure, and not surprisingly, I get this:

```
 mlstats --db-user ** --db-password ** --db-name mlstats_linux --report-file=/home/dawn/log_files/lkml.txt "http://dir.gmane.org/gmane.linux.kernel"
Retrieving http://download.gmane.org/gmane.linux.kernel/2167380/2169380...
Retrieving http://download.gmane.org/gmane.linux.kernel/2169380/2171380...
Analyzing /home/dawn/.mlstats/compressed/dir.gmane.org/gmane.linux.kernel/2167380

***WARNING: 1462 messages (out of 1533) parsed but not stored (1462 duplicate, 0 errors)***
1533 messages analyzed
71 messages stored in database mlstats_linux
0 messages ignored by the parser
WARNING: Some messages were parsed but not stored
```

The 1082 files in ~/.mlstats/compressed/dir.gmane.org/gmane.linux.kernel contain data. The file sizes range from 8.0M on the high end and 2.0M on the low end with the exception of the file 0, which contains a few chars of junk and is only 22B. 

Is there any way to force it to start the analysis at a specific file? (I think offset is just for downloads?)

**Comment by geekygirldawn** [comment]
One more detail. I've also been deleting the line in the compressed_files table of the database to try to get it to forget where it was and start over. I've done this between every run with no difference.

```
MariaDB [mlstats_linux]> select * from compressed_files where mailing_list_url="http://dir.gmane.org/gmane.linux.kernel";
+------------------------------------------------------+-----------------------------------------+---------+---------------------+
| url                                                  | mailing_list_url                        | status  | last_analysis       |
+------------------------------------------------------+-----------------------------------------+---------+---------------------+
| http://download.gmane.org/gmane.linux.kernel/2167380 | http://dir.gmane.org/gmane.linux.kernel | visited | 2016-03-04 10:01:29 |
+------------------------------------------------------+-----------------------------------------+---------+---------------------+
1 row in set (0.00 sec)

MariaDB [mlstats_linux]> delete from compressed_files where mailing_list_url="http://dir.gmane.org/gmane.linux.kernel";
Query OK, 1 row affected (0.00 sec)

MariaDB [mlstats_linux]> select * from compressed_files where mailing_list_url="http://dir.gmane.org/gmane.linux.kernel";
Empty set (0.00 sec)
```

**Comment by gpoo** [comment]
I think that is a different problema. May you open a new issue? (I will take a look at it once I have a little of time)
